docs:
  categorize_library: true
  categorize_verify: false
  html: false
  toc: false
plugins:
- jemoji
- jekyll-remote-theme
remote_theme: jekyll/minima
theme: jekyll-theme-minimal

title: sotanishy's competitive programming library
author: sotanishy
description: sotanishy's code snippets for competitive programming

